server:
  port: 18084

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: lb://order
          predicates:
            - Path=/order/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18080/eureka/
  instance:
    instance-id: gateway-${server.port}
